<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="10" hostname="DESKTOP-4EFQLTI" name="appium_Package.TestNG" tests="11" failures="0" timestamp="2020-02-27T10:57:28 GMT" time="0.092" errors="1">
  <testcase name="f" time="0.000" classname="appium_Package.TestNG">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.000" classname="appium_Package.TestNG">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.000" classname="appium_Package.TestNG">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.000" classname="appium_Package.TestNG">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.000" classname="appium_Package.TestNG">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.000" classname="appium_Package.TestNG">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.000" classname="appium_Package.TestNG">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="setupAppium" time="0.092" classname="appium_Package.TestNG">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at io.appium.java_client.AppiumDriver.updateDefaultPlatformName(AppiumDriver.java:163)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
at appium_Package.TestNG.setupAppium(TestNG.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:345)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setupAppium -->
  <testcase name="f" time="0.000" classname="appium_Package.TestNG">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.000" classname="appium_Package.TestNG">
    <skipped/>
  </testcase> <!-- f -->
  <testcase name="f" time="0.000" classname="appium_Package.TestNG">
    <skipped/>
  </testcase> <!-- f -->
</testsuite> <!-- appium_Package.TestNG -->
